### ISSUE TITLE
Explore VuePress Alternatives

### ISSUE THREAD

**Issue by dgilleland** [dgilleland/dgilleland.github.io#43]
I went towards VuePress years ago because I wanted:

- Markdown content
- Custom elements" (via components)

Things to try

- [x] ~~**VitePress** - *the successor to VuePress*~~
- [x] #46
  - > **Resolved!** :+1: ~~*A major dislike I have for Astro is that it's handling of image paths does **not** honour the markdown syntax for images. It's probably a deal breaker for me.*~~
  - [x] Vite
  - [x] [MDX](https://storybook.js.org/docs/react/api/mdx) files?
  - [x] Markdoc? ala Stripe - https://stripe.com/blog/markdoc
  - [x] Svelte? (with [StoryBook](https://storybook.js.org/blog/storybook-for-sveltekit/)

**Comment by dagilleland** [comment]
I've followed the VitePress setup guide, and there are a few items to still explore before deciding on a switch to VitePress

- [ ] Fixing the link for the `/new/` page
- [ ] Exploring what is/isn't built in as far as MarkDown features (esp. those GFM that I', beginning to love)
  - [ ] Checkbox tasks
  - [ ] MathJax/TexMath
  - [ ] Mermaid diagrams
  - [ ] Whether or not I should use any of the Markdown extensions....
- [ ] Deploying to GitHub Pages with an action. See recommendations in the [VitePress docs](https://vitepress.vuejs.org/guide/deploy.html#github-pages). Also relates to issue #44
- [ ] A Vue SSR component that  will replace the one for coloring my teaching schedule.
  - :musical_note: This is where some of the MDX stuff might be better, and I would probably prefer to use Svelte instead of Vue for this.

**Comment by dgilleland** [comment]
With Astro, I get the remaining items I'm looking for: Markdown, Math/Mermaid/etc. diagrams, MDX, Markdoc, Svelte (& others), Vite, Vitest. I think I've actually found a solution that I would use! Who woulda thot!?
